# Generated by Django 4.1.3 on 2022-11-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
